### ISSUE TITLE
Seattle CO Tournament failed to generate pairings for fourth round

### ISSUE THREAD

**Issue by marckubischta** [Project-NISEI/cobra#136]
https://cobr.ai/tournaments/2988
Contact `@Whiteblade111#5606` or `@Maninthemoon(Abraham)#8507` on Discord for additional details.

**Comment by maninthem00n** [comment]
We couldn't get round 4 to pair. We got an error message and it looked as if nothing had changed, but when we left the page and retuned to the tournament we had a "round" with non of the pairings. We tried deleting and repairing the 4th round about 6 times. We tried clearing the cache and reloading the browser, but we couldn't get anything to work. so we paired the old fashioned way with paper.

The bug is still active with [Canadian Rematch CO](https://cobr.ai/tournaments/2988/rounds/12755) on cobr.ai

<img width="744" alt="Screen Shot 2023-05-25 at 9 02 53 AM" src="https://github.com/Project-NISEI/cobra/assets/88176407/c609efe7-fdc6-41ef-8d5a-7be36060af4c">
<img width="762" alt="Screen Shot 2023-05-25 at 9 03 10 AM" src="https://github.com/Project-NISEI/cobra/assets/88176407/50efeefa-dabb-40de-a4be-49d5055108ee">

**Comment by haradan** [comment]
It looks like the problem is to do with a 2-for-1 in round 3. Here are some of the logs from one of the times you tried to pair a new round:

```
I, [2023-05-21T00:32:03.399535 #7]  INFO -- : [88028446-f190-4696-a910-e57ff0fc5254] Started POST "/tournaments/2988/rounds" for 73.109.110.54 at 2023-05-21 00:32:03 +0000
...
I, [2023-05-21T00:32:03.668610 #7]  INFO -- : [88028446-f190-4696-a910-e57ff0fc5254] Completed 500 Internal Server Error in 267ms (ActiveRecord: 35.0ms | Allocations: 59076)
F, [2023-05-21T00:32:03.670017 #7] FATAL -- : [88028446-f190-4696-a910-e57ff0fc5254]   
[88028446-f190-4696-a910-e57ff0fc5254] TypeError (nil can't be coerced into Integer):
[88028446-f190-4696-a910-e57ff0fc5254]   
[88028446-f190-4696-a910-e57ff0fc5254] app/models/player.rb:33:in `points'
[88028446-f190-4696-a910-e57ff0fc5254] app/services/pairing_strategies/swiss.rb:33:in `paired_players'
[88028446-f190-4696-a910-e57ff0fc5254] app/services/pairing_strategies/swiss.rb:9:in `pair!'
[88028446-f190-4696-a910-e57ff0fc5254] app/services/pairer.rb:10:in `pair!'
[88028446-f190-4696-a910-e57ff0fc5254] app/models/round.rb:14:in `pair!'
[88028446-f190-4696-a910-e57ff0fc5254] app/models/stage.rb:18:in `block in pair_new_round!'
[88028446-f190-4696-a910-e57ff0fc5254] app/models/stage.rb:17:in `pair_new_round!'
[88028446-f190-4696-a910-e57ff0fc5254] app/models/tournament.rb:12:in `pair_new_round!'
[88028446-f190-4696-a910-e57ff0fc5254] app/controllers/rounds_controller.rb:18:in `create'
```

Nathan's score in the round 3 2-for-1 was somehow recorded as nil instead of 0. It's failed to read that score when it tried to pair the new round. I'll see if I can fix it for future 2-for-1s.

**Comment by haradan** [comment]
It's not the 2-for-1, it's just if you type in the scores manually and leave one player's score empty, it records it as nil for it to choke on later. I'll stop it doing that.
