### ISSUE TITLE
Docker compose locally fails after initially working

### ISSUE THREAD

**Issue by shdblowers** [Project-NISEI/cobra#273]
Hi, seem to be running into an issue where when running locally with docker compose, after it initially works, I come back after a reboot and then the app fails to start, only output I get is the following, not sure where to go with debugging it.

```
$ docker compose up
WARN[0000] /home/steven/sandbox/cobra/docker-compose.yml: `version` is obsolete
WARN[0000] /home/steven/sandbox/cobra/docker-compose.override.yml: `version` is obsolete
[+] Running 3/1
 ✔ Network cobra_default  Created                                                                               0.1s
 ✔ Container cobra-db-1   Created                                                                               0.0s
 ✔ Container cobra-app-1  Created                                                                               0.0s
Attaching to app-1, db-1
db-1   |
db-1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
db-1   |
db-1   | 2024-03-26 14:09:01.990 UTC [1] LOG:  starting PostgreSQL 14.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, 64-bit
db-1   | 2024-03-26 14:09:01.990 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1   | 2024-03-26 14:09:01.990 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1   | 2024-03-26 14:09:01.994 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1   | 2024-03-26 14:09:01.999 UTC [21] LOG:  database system was shut down at 2024-03-26 14:06:48 UTC
db-1   | 2024-03-26 14:09:02.002 UTC [1] LOG:  database system is ready to accept connections
app-1 exited with code 0
app-1 exited with code 0
app-1 exited with code 0
app-1 exited with code 1
```

**Comment by haradan** [comment]
You can find out what happened in the app container by checking the contents of the "cobra-logs" volume. It'll be in Docker as "cobra_cobra-logs". It should have a couple of log files you can check.

**Comment by shdblowers** [comment]
This is what I get in file `unicorn.stderr.log`:

```
bundler: failed to load command: unicorn (/var/www/bundle/ruby/3.2.0/bin/unicorn)
/var/www/bundle/ruby/3.2.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:206:in `pid=': Already running on PID:1 (or pid=/var/www/cobra/tmp/pids/unicorn.pid is stale) (ArgumentError)

        raise ArgumentError, "Already running on PID:#{x} " \
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /var/www/bundle/ruby/3.2.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:138:in `start'
        from /var/www/bundle/ruby/3.2.0/gems/unicorn-6.1.0/bin/unicorn:128:in `<top (required)>'
        from /var/www/bundle/ruby/3.2.0/bin/unicorn:25:in `load'
        from /var/www/bundle/ruby/3.2.0/bin/unicorn:25:in `<top (required)>'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `load'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
bundler: failed to load command: unicorn (/var/www/bundle/ruby/3.2.0/bin/unicorn)
/var/www/bundle/ruby/3.2.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:206:in `pid=': Already running on PID:1 (or pid=/var/www/cobra/tmp/pids/unicorn.pid is stale) (ArgumentError)

        raise ArgumentError, "Already running on PID:#{x} " \
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /var/www/bundle/ruby/3.2.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:138:in `start'
        from /var/www/bundle/ruby/3.2.0/gems/unicorn-6.1.0/bin/unicorn:128:in `<top (required)>'
        from /var/www/bundle/ruby/3.2.0/bin/unicorn:25:in `load'
        from /var/www/bundle/ruby/3.2.0/bin/unicorn:25:in `<top (required)>'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `load'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
bundler: failed to load command: unicorn (/var/www/bundle/ruby/3.2.0/bin/unicorn)
/var/www/bundle/ruby/3.2.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:206:in `pid=': Already running on PID:1 (or pid=/var/www/cobra/tmp/pids/unicorn.pid is stale) (ArgumentError)

        raise ArgumentError, "Already running on PID:#{x} " \
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /var/www/bundle/ruby/3.2.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:138:in `start'
        from /var/www/bundle/ruby/3.2.0/gems/unicorn-6.1.0/bin/unicorn:128:in `<top (required)>'
        from /var/www/bundle/ruby/3.2.0/bin/unicorn:25:in `load'
        from /var/www/bundle/ruby/3.2.0/bin/unicorn:25:in `<top (required)>'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `load'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
bundler: failed to load command: unicorn (/var/www/bundle/ruby/3.2.0/bin/unicorn)
/var/www/bundle/ruby/3.2.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:206:in `pid=': Already running on PID:1 (or pid=/var/www/cobra/tmp/pids/unicorn.pid is stale) (ArgumentError)

        raise ArgumentError, "Already running on PID:#{x} " \
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /var/www/bundle/ruby/3.2.0/gems/unicorn-6.1.0/lib/unicorn/http_server.rb:138:in `start'
        from /var/www/bundle/ruby/3.2.0/gems/unicorn-6.1.0/bin/unicorn:128:in `<top (required)>'
        from /var/www/bundle/ruby/3.2.0/bin/unicorn:25:in `load'
        from /var/www/bundle/ruby/3.2.0/bin/unicorn:25:in `<top (required)>'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `load'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli/exec.rb:23:in `run'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:451:in `exec'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:34:in `dispatch'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/cli.rb:28:in `start'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/exe/bundle:28:in `block in <top (required)>'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /var/www/bundle/ruby/3.2.0/gems/bundler-2.5.6/exe/bundle:20:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'

```

**Comment by haradan** [comment]
There's a solution for that at the end of the readme, here:

https://github.com/Project-NISEI/cobra/blob/main/README.md#bug-troubleshooting

It should also be solved by a recent change to switch from Unicorn to Puma for the web server. Puma also has a similar PID file, but there's now a script that runs when the container starts up that deletes it if it already exists. That change is on the latest version of the main branch.

Does that solve your problem?
